version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven...
      - apt-get update
      - apt-get install -y maven
      - mvn -version

  pre_build:
    commands:
      - echo Pre-build phase started...

  build:
    commands:
      - echo Running unit tests...
      - mvn clean test
      - echo Building WAR package...
      - mvn package

  post_build:
    commands:
      - echo Build completed on data
artifacts:
  files:
    - target/*.war
  discard-paths: yes
